const ObJs = require('./literals/objetos')
const Obj = require("./literals/objeto.json")
const Pessoa = require("./class/anatomia")
    // console.log(Obj)
    // console.log(ObJs.getFinalPrice())
console.log(Pessoa.hello("Jeovane", "dev", 23))